### ISSUE TITLE
LPS加载CreateDLL.dll出错

### ISSUE THREAD

**Issue by xiaofengi** [zhang-can/EasyPR-DLL-CSharp#4]
用vs2017和opencv3.1已经成功生成CreateDLL.dll了，但是调用的时候GetDelegateForFunctionPointer方法的api句柄参数却是空的，我控制台输出了hLib这个句柄，值是0，是不是表示加载dll出错了？

**Comment by zhang-can** [comment]
对的，需要查一下C#项目引用的dll路径是否正确~

**Comment by xiaofengi** [comment]
现在我换成vs2013这问题解决了，但是现在lps(file_name, 2)出现System.AccessViolationException异常，换成vs2015还是没解决，netsh winsock reset和.net换成4.6都试过了没起作用，请问下知道什么原因引起的吗？

**Comment by zhang-can** [comment]
抱歉，这个问题没遇到过哈~你可以去群里问问有没有人遇到过类似的问题。
