### ISSUE TITLE
error C1083: 无法打开包括文件: “easypr/core/chars_identify.h”: No such file or directory

### ISSUE THREAD

**Issue by Ixiaohuihuihui** [zhang-can/EasyPR-DLL-CSharp#5]
您好，我想问一下为什么会出现这种问题：
error C1083: 无法打开包括文件: “easypr/core/chars_identify.h”: No such file or directory

我已经按照您的说明一步一步往下做了~

**Comment by foreverhot1019** [comment]
找到“属性” --> “C/C++” -->  “附加包含目录”，点击右面的下拉三角图标，选择“编辑”，添加以上报错文件目录即可。

**Comment by codevvvv9** [comment]
@dlhhuihuihui 你好啊，你把C#版本跑通了吗

**Comment by Ixiaohuihuihui** [comment]
您好，我已经成功运行 1577884743 邮箱：1577884743@qq.com 签名由 网易邮箱大师 定制 在2018年03月22日 22:19，吴少 写道： @dlhhuihuihui 你好啊，你把C#版本跑通了吗 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
