### ISSUE TITLE
无法打开图片，../../../../x64/Release/CreateDLL.dll无法导入

### ISSUE THREAD

**Issue by Ten000hours** [zhang-can/EasyPR-DLL-CSharp#8]
代码中有相对地址‘../../../../x64/Release/CreateDLL.dll’，请问这个应该如何更改？

>  private void button1_Click(object sender, EventArgs e)
>         {
>             this.label1.Text = "正在处理中，请稍等......";
>             Application.DoEvents();
>             DllInvoke dll = new DllInvoke(@"../../../../x64/Release/CreateDLL.dll");
>             do_lps_func lps = (do_lps_func)dll.Invoke("do_lps", typeof(do_lps_func));
> 
>             //folder_path = @"L:\Users\zc\Desktop\native_test";
>             DirectoryInfo TheFolder = new DirectoryInfo(folder_path);

**Comment by wowowo110** [comment]
先从新生成creatdll

**Comment by foreverhot1019** [comment]
1：可以将 CreateDLL.dll 和 opencv_world310.dll ，opencv_world310d.dll 放到System32目录下，就可以了；
2：DLLImport（LoadLibrary不行，貌似 跟环境有关系，缺少一些lib或者dll）
 #region CreateDLL API

        [DllImport("E:\\练习\\EasyPR-DLL-CSharp-master\\x64\\Release\\CreateDLL.dll", EntryPoint = "do_lps")]
        public extern static int do_lps(string path, IntPtr Num);

        [DllImport("E:\\练习\\EasyPR-DLL-CSharp-master\\x64\\Release\\CreateDLL.dll", EntryPoint = "get_license_str")]
        public extern static IntPtr get_license_str();

        [DllImport("E:\\练习\\EasyPR-DLL-CSharp-master\\x64\\Release\\CreateDLL.dll", EntryPoint = "get_color_str")]
        public extern static IntPtr get_color_str();

        #endregion

**Comment by beewolf2018** [comment]
2.添加环境变量：[opencv安装目录]\opencv\build\x64\vc12\bin

**Comment by daluanren** [comment]
增加环境变量后还是报这个错误，是跟64位和32位有关么？

**Comment by daluanren** [comment]
增加环境变量后，还是出错。
我用的是VS2015，添加环境变量：[opencv安装目录]\opencv\build\x64\vc14\bin

**Comment by Michael-Lee-Wang** [comment]
使用管理员权限运行,即可
